### ISSUE TITLE
Amout fonction

### ISSUE THREAD

**Issue by tricastor** [xdevguild/piggy-bank-sc#2]
Nice job, very interesting. Nevertheless, the "amount" function is missing in the code, I'm interesting to know how you'd do this. Something like: 
```
  #[endpoint(amount)]
  fn amount(&self) -> SCResult<()> {
    let caller = &self.blockchain().get_caller();
    let caller_address = caller.to_address();
    self.locked_amount(&caller_address).get();
    Ok(())
  }
```
but I don't know how to return the amount as a data of the transaction... thank you for this anyway !

**Comment by juliancwirko** [comment]
Hey, this is not needed. There is already a possibility to use queries directly from the storage. In that case, you don't have to make the transaction and pay fees:

```
 #[view(getLockedAmount)]
 #[storage_mapper("lockedAmount")]
 fn locked_amount(&self, piggy_owner: &Address) -> SingleValueMapper<BigUint>;
```

You can read more about it here:
- https://docs.elrond.com/sdk-and-tools/rest-api/virtual-machine/
- https://github.com/ElrondNetwork/elrond-sdk-erdjs#querying-smart-contracts
